### ISSUE TITLE
Grouping solutions

### ISSUE THREAD

**Issue by Mohameddekow** [Devabubakar/LCGrind#4]
hello guyz.
are there contribution guidelines on how we can group all other leetcode solutions other than the blind 75 once.
like having **Arrays package** , **trees package** and so on.

**Comment by Devabubakar** [comment]
Hi, Your idea of grouping Leet Code solutions into specific categories like Arrays, Trees, etc. is fascinating. It's something that we have also considered doing in the past. Our current focus is on answering [Microsoft Commonly Asked Questions](https://raw.githubusercontent.com/Devabubakar/LCGrind/main/MS.md) which we utilize as mock interview questions when we meet in person on our campus. We have opted not to separate the questions into themes for the time being, since it allows us to cover a greater range of patterns and topics in a shorter amount of time. However, once we have completed solving all the questions, we want to divide them into specific subjects for easier reference. In the meantime, All other resources like blind 75 can be grouped according to their topics/patterns . Thanks
